### ISSUE TITLE
Doesn't seem to work on a few users

### ISSUE THREAD

**Issue by a4pumpkin** [Kent-Lee/artstation-scraper#4]
Hi, I've noticed that the scraper won't grab all the images for a few users:

https://www.artstation.com/timbougami
https://www.artstation.com/flaptrapsart

Tried it with about 30 different artists, and it's worked flawlessly otherwise. It's really useful, thanks a ton for putting this together 😄 

Also apologies if I should have posted in the other thread, I wasn't sure

**Comment by evanerichards** [comment]
Same.

Got this error:
Traceback (most recent call last):
  File "E:\artstation-scraper\main.py", line 53, in <module>
    main()
  File "E:\artstation-scraper\main.py", line 49, in main
    download_artists(api, config)
  File "E:\artstation-scraper\main.py", line 9, in download_artists
    result = api.save_artists(config.artists, config.save_dir)
  File "E:\artstation-scraper\lib\artstation.py", line 106, in save_artists
    files = self.save_artist(id, dir_path)
  File "E:\artstation-scraper\lib\artstation.py", line 88, in save_artist
    artist_name = self.artist(artist_id)["name"]
  File "E:\artstation-scraper\lib\artstation.py", line 33, in artist
    res = self.request("GET", f"https://{artist_id}.artstation.com")
  File "E:\artstation-scraper\lib\artstation.py", line 29, in request
    res.raise_for_status()
  File "C:\Users\myself\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://artistname.artstation.com/
